"""Immutable deployment records and model resolution."""

from tinyllm.deployment.evaluation_subject import (
    M9EvaluationSubjectRecord,
    M10StageEvaluationSubjectRecord,
    ResolvedEvaluationSubject,
    ServingModel,
    effective_artifact_sha256,
    evaluation_artifact_sha256,
    evaluation_subject_id,
    m10_stage_evaluation_subject_id,
    publish_evaluation_subject,
    publish_m10_stage_evaluation_subject,
    resolve_evaluation_subject,
    resolve_m10_stage_evaluation_subject,
    resolve_serving_model,
)
from tinyllm.deployment.evidence_schema import (
    M7ContractEvidence,
    M7PackageVersion,
    M7RecoveryEvidence,
    M7RollbackEvidence,
    M7SecurityAudit,
    M7ServingEnvironment,
    M7ServingHardware,
    M7VulnerabilityAssessment,
)
from tinyllm.deployment.registry import (
    DeploymentError,
    DeploymentErrorCode,
    load_production_gate,
    promote_production,
    resolve_model,
    rollback_production,
    show_deployment,
)
from tinyllm.deployment.schema import (
    M7GateCheck,
    M7ProductionAlias,
    M7ProductionGate,
    M7ProductionRecord,
    ResolvedModel,
)

__all__ = [
    "DeploymentError",
    "DeploymentErrorCode",
    "M7ContractEvidence",
    "M7GateCheck",
    "M7ProductionAlias",
    "M7ProductionGate",
    "M7ProductionRecord",
    "M7RecoveryEvidence",
    "M7RollbackEvidence",
    "M7SecurityAudit",
    "M7ServingEnvironment",
    "M7ServingHardware",
    "M7PackageVersion",
    "M7VulnerabilityAssessment",
    "M9EvaluationSubjectRecord",
    "M10StageEvaluationSubjectRecord",
    "ResolvedEvaluationSubject",
    "ResolvedModel",
    "ServingModel",
    "effective_artifact_sha256",
    "evaluation_artifact_sha256",
    "evaluation_subject_id",
    "m10_stage_evaluation_subject_id",
    "load_production_gate",
    "promote_production",
    "resolve_model",
    "resolve_evaluation_subject",
    "resolve_m10_stage_evaluation_subject",
    "resolve_serving_model",
    "publish_evaluation_subject",
    "publish_m10_stage_evaluation_subject",
    "rollback_production",
    "show_deployment",
]
